package com.example.enfermeria.controller;

import java.util.ArrayList;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.example.enfermeria.EnfermeriaApplication;
import com.example.enfermeria.dao.NurseRepository;
import com.example.enfermeria.entity.Nurse;

@RestController
@RequestMapping("/nurse")
public class NurseController {
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private NurseRepository nurseRepository;

    public NurseController(NurseRepository nurseRepository) {
        this.nurseRepository = nurseRepository;
    }
	
	/*@PostMapping("/login")
    public ResponseEntity<Boolean> login(@RequestBody Nurse loginRequest) {
    	String usr = loginRequest.getUser();
    	String pw = loginRequest.getPassword();
    	
    	for (Nurse nurses : nurseList) {
    		if (nurses.getUser().equals(usr) && nurses.getPassword().equals(pw)) {
    			return ResponseEntity.ok(true);
    		}
    	}
    	return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(false);
    }
	
	@GetMapping("/index")
	public ResponseEntity<ArrayList<Nurse>> getAll(){
		return ResponseEntity.ok(nurseList);
	}*/
	
	@GetMapping("/name")
    public ResponseEntity<Nurse> findByName(@RequestParam("name") String name) {
		try {
			Optional<Nurse> nurse = nurseRepository.findByNameIgnoreCase(name);

	        if (nurse.isPresent()) {
	            return ResponseEntity.ok(nurse.get());
	        } else {
	            return ResponseEntity.notFound().build();
	        }
		} catch (Exception e) {
			return ResponseEntity.noContent().build();
		}
        
    }
}