package com.example.enfermeria.controller;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.example.enfermeria.EnfermeriaApplication;
import com.example.enfermeria.dao.NurseRepository;
import com.example.enfermeria.entity.Nurse;

@RestController
@RequestMapping("/nurse")
public class NurseController {
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private NurseRepository nurseRepository;
	
	@PostMapping("/login")
    public @ResponseBody boolean login(@RequestBody Nurse loginRequest) {		
		String user = loginRequest.getName();
		String password = loginRequest.getPassword();
    	
		Optional<Nurse> nurse = nurseRepository.findByUser(user);
		if (nurse.isPresent() && nurse.get().getPassword().equals(password)) {
		    return true;
		}
		return false;
    }
	/*
	@GetMapping("/index")
	public ResponseEntity<ArrayList<Nurse>> getAll(){
		return ResponseEntity.ok(nurseList);
	}
	
	@GetMapping("/name")
	public ResponseEntity<Nurse> findByName(@RequestParam(value = "name") String name) {

		for (int i = 0; i < nurseList.size(); i++) {
			if (name.equalsIgnoreCase(nurseList.get(i).getName())) {
				return ResponseEntity.ok(nurseList.get(i));
			}
		}
		return ResponseEntity.notFound().build();
	}
	*/
}